### ISSUE TITLE
IDE Support for application properties

### ISSUE THREAD

**Issue by MichaelVonB** [holunda-io/camunda-bpm-taskpool#1007]
### Scenario

* camunda-bpm-taskpool version: current
* Camunda BPM version: current
* Description of your use case: When configuring polyflow with application.yml (or application.properties) in my spring-boot project I want to have support for confiuguration parameters

### Current Behaviour
I get a warning in my IDE telling me: "Cannot resolve configuration property 'polyflow.view.jpa.payload-attribute-level-limit'".
This also applies to all other properties 

### Wanted Behaviour
- Don't have a warning
- Have autocomplete Support
- Be able to read JavaDoc

### Possible Workarounds
- Ignore warnings 😅

**Comment by zambrovski** [comment]
I believe there are two issues here. 
- IntelliJ support: found the reason. The spring-boot-annotation processor must be as an optional dependency on the classpath.
- Generation of properties automatically: on it...
