### ISSUE TITLE
Consolidate event collected in one transaction

### ISSUE THREAD

**Issue by zambrovski** [holunda-io/camunda-bpm-taskpool#105]
Currently, events are fired in Camunda defined order and historic events are fired before the initial creation events. In order to cope with this situation, we want to be able to reorder or even drop unnecessary events.

**Comment by zambrovski** [comment]
The idea is:

- collect all commands sent by the engine during one transaction
- save them in a thread-local store
- group by task id (there my be more than one task involved, when we complete one task and create another)
- process the result after transaction commit
  - determine the real intent (create, assign, complete, delete, update)
  - create exactly one command representing all state change of the intent (project all changes to one)
- clean-up the thread local store

Some ideas on implementation:
- will use reflection and dataclass copy 
- after this change, we can simplify the core, by removing the InitialCommand workaround
- the amount of commands and events sent should be drastically reduced (currently some operations in the engine originate up to 8 commands)
- development happens on a separate feature branch

**Comment by a-hegerath** [comment]
@zambrovski, could you publish your already made changes for this on a new feature branch? I would continue working on it today/tomorrow. Or are you currently implementing changes and it does not make sense to parallel the development at this stage?

**Comment by zambrovski** [comment]
It is pushed into `feature/commans_accumulator` branch. I'm pretty far and currently two features are missing:
- Sort the messages (my first estimate was to invert the order, but have a look on the order for common intents create/complete). I believe we need a determined logic which does the sorting.
- Project values of a certain field to latest taken from the list of sorted messages. I believe a generic property-accessing reflection-based approach is needed here.

Feel free to contact me in slack for more details
