### ISSUE TITLE
Task pool service drops assignee when handling a TaskAttributeUpdatedEngineEvent

### ISSUE THREAD

**Issue by a-hegerath** [holunda-io/camunda-bpm-taskpool#109]
Since release 1.2.0, the TaskAttributeUpdatedEngineEvent does not contain the assignee property any more (by design). The task pool service needs to use the assignee of the existing task when creating a new task object, but does not. 

See:
fun task(event: TaskAttributeUpdatedEngineEvent, task: Task)

**Comment by zambrovski** [comment]
fixed with #b8df2be
