### ISSUE TITLE
SubscriptionQuery for "TaskWithDataEntries" is not updated on DataEntryChange

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/camunda-bpm-taskpool#141]
Simple View:
- The taskLifecycle changes emit an update for `TasksWithDataEntriesForUserQuery`, but the DataEntry[Created|Updated] handler do not

MongoView:
- The `TasksWithDataEntriesForUserQuery` does not get any updates at all.
- Also, a deleted task will currently not trigger any subscription query updates.

**Comment by lbilger** [comment]
Also, in the Mongo View, the `TasksWithDataEntriesForUserQuery` does not get any updates at all.
Also, a deleted task will currently not trigger any subscription query updates.
