### ISSUE TITLE
Taskpool Cockpit frontend becomes very slow

### ISSUE THREAD

**Issue by zambrovski** [holunda-io/camunda-bpm-taskpool#147]
Using cockpit with several hundreds of tasks (and about a thousand of events) seems to break the frontend performance. The browser becomes very slow and non-responsive.

**Comment by zambrovski** [comment]
One idea why this happens is, that the provisioning of events from the stream one-by-one leads the observable to update the UI (due to the change-detection) one-by-one which creates a too high load inside the browser. If this is true, some magic RXJS operation with a de-bounce semantic (not to react on every change, but on changes per time span) should help....

**Comment by lbilger** [comment]
bufferTime (https://www.learnrxjs.io/operators/transformation/buffertime.html) should be what we‘re looking for...

**Comment by zambrovski** [comment]
> bufferTime (https://www.learnrxjs.io/operators/transformation/buffertime.html) should be what we‘re looking for...

Can you help here?
