### ISSUE TITLE
Upgrade libraries

### ISSUE THREAD

**Issue by zambrovski** [holunda-io/camunda-bpm-taskpool#179]
The libraries to upgrade are:
[ ] SpringBoot
[ ] Camunda
[ ] SpringBoot Starter
[ ] Angular
[x] AxonFramework
[ ] Kotlin 
[ ] Jackson

**Comment by zambrovski** [comment]
Serialization test is broken...

**Comment by a-hegerath** [comment]
The serialization test could be fixed easily by moving the data class `Pojo` that is to be serialized out of the test function, but still it would be good if we understood what exactly makes the test fail.
