### ISSUE TITLE
Could not find artifact io.holunda.taskpool:camunda-bpm-taskpool-example-tasklist-backend:jar:2.0.4

### ISSUE THREAD

**Issue by rameshsr** [holunda-io/camunda-bpm-taskpool#204]
Using the latest 2.0.4 release version of the source. Following the Quick Start Guide as given below.

git clone https://github.com/holunda-io/camunda-bpm-taskpool.git
cd camunda-bpm-taskpool
./.docker/setup.sh
docker-compose up
./mvn spring-boot:run -f examples/taskpool-application

But the last step (mvn command) is failing with the following exception

Could not find artifact io.holunda.taskpool:camunda-bpm-taskpool-example-tasklist-backend:jar:2.0.4 in central (https://repo.maven.apache.org/maven2)

How do we resolve this?

**Comment by zambrovski** [comment]
please build of the project, before you run it.

So run `./mvnw clean install` before then running
`./mvnw spring-boot:run -f examples/taskpool-application`

**Comment by zambrovski** [comment]
Thank you for reporting. There is obviously a bad description in the docs, I'll fix it ASAP.
