### ISSUE TITLE
Restructure documentation

### ISSUE THREAD

**Issue by zambrovski** [holunda-io/camunda-bpm-taskpool#212]
Create better documentation and fill the component sections.

**Comment by zambrovski** [comment]
@joehm please review the docs http://www.holunda.io/camunda-bpm-taskpool/ and feel free to give me some feedback. Let us start a discussion how to make a better documentation.

**Comment by joehm** [comment]
in progress...

**Comment by zambrovski** [comment]
- updated the orchid version and added additional section to user guide. 
- add description of singlenode scenario
- fixed description of distributed with axon server scenario

**Comment by zambrovski** [comment]
I'll close this generic issue in favor of smaller documentation issues.
