### ISSUE TITLE
Separate event handling from query handling in (Mongo) projection

### ISSUE THREAD

**Issue by a-hegerath** [holunda-io/camunda-bpm-taskpool#225]
This is currently just an idea for discussion. What I want to achieve is that I can deploy a tasklist application (in my case with the mongo-based projection, but the idea is the same for any projection) so that queries are handled but events are not (or the other way around).

That way, one could better scale the tasklist application horizontally if the query handling load is highly different from the event handling load.
Also, the tasklist could be up and running in a "read-only mode", which would be helpful if there are maintenance operations that should not be disturbed by incoming task events (for example, migrating a tracking token to a different representation).

On an API level, the query logic is contained in the interfaces TaskApi and DataEntryApi and its reactive counterparts ReactiveTaskApi and ReactiveDataEntryApi. For event handling there is currently no dedicated interface. The view implementations (for example TaskPoolMongoService) simply implement all query and event handling methods. It should not be too difficult to have two different service classes, one for query handling and another for event handling, and conditionally have the one, the other, or both instantiated by Spring.

**Comment by zambrovski** [comment]
Thank you for the valuable idea. I think it is worth to do so and separate the read part from the write part. Are you going to provide a pull request?

**Comment by zambrovski** [comment]
I think this is not needed, since you can just deploy the view twice and skip the configuration of the Kafka consumer on the view-only part.
