### ISSUE TITLE
Remove taskpool-task when remoteTask is ended via boundary event

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/camunda-bpm-taskpool#39]
I asked this question in the forum: https://forum.camunda.org/t/hook-when-usertask-is-ended-by-boundary-event/9302  and it seems to be a use case, that taskpool also will have to address.

**Comment by zambrovski** [comment]
So if I understand you correctly, the delete event is not fired. 

The question is: do we want to fix an onvious Camunda Bug with the taskpool, or just switch to history events for other reasons?

**Comment by jangalinski** [comment]
false alarm, created a minimal working test ... everything as expected ... 

https://gist.github.com/jangalinski/82074a77930f5734bca32845208d3ae1
