### ISSUE TITLE
The include in PolyflowJpaViewProperties will only apply attributes with depth of 1 

### ISSUE THREAD

**Issue by d-oldenburg** [holunda-io/camunda-bpm-taskpool#445]
### Steps to reproduce

* camunda-bpm-taskpool version: 3.1.4
* Open JpaPolyflowViewDataEntryService and check if all filters set.
* Now check the table `plf_data_entry_payload_attributes`
* attributes with depth greater than one are not present (but attention for `exclude` attributes the behaviour is as expected) 

### Expected behaviour
All values given in the configuration for the include of the configuration `PolyflowJpaViewProperties` should be applied and written in the database table `plf_data_entry_payload_attributes`.

### Actual behaviour
In the module polyflow-view-jpa the include of the configuration `PolyflowJpaViewProperties` will only accept values with depth size of 1 to the database table `plf_data_entry_payload_attributes`. All depths greater than 1 won't be applied to it. 

## Problem description 
If you configure `PolyflowJpaViewProperties` via with the following yaml-snippet in your application.yaml:  
```
polyflow.view.jpa:
  stored-items: data-entry
  data-entry-filters:
    include: first, second, third.foo, third.fooTwo
```
only the first two attributes (`first` and `second` ) are used to write values into the table `plf_data_entry_payload_attributes`.

**Comment by zambrovski** [comment]
Closed by adafb924dc1c33
