### ISSUE TITLE
Bundle taskpool/datapool with axon server

### ISSUE THREAD

**Issue by zambrovski** [holunda-io/camunda-bpm-taskpool#47]

**Comment by jangalinski** [comment]
This will have to wait until the axonserver sources are available, it is not possible to use the executable axonserver-4.0.jar as a dependency, so we cannot embed.

**Comment by zambrovski** [comment]
I don't think it is a good idea from the point of view of infrastructure lifecycle. Axon Server is a piece of infrastructure (like a database system) and the taskpool is a pure backend system. They have different requirements on operations, backup, etc...

**Comment by jangalinski** [comment]
Totally agree regarding ops. Once we have the server on github, it would be nice to investigate bundling for dev/test, but that does not have to be a taskpool issue (today)
