### ISSUE TITLE
TasksWithDataEntriesForUserQuery is not serializable / can not be serialized to json

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/camunda-bpm-taskpool#560]
### Steps to reproduce

Use the configured axon serializer to serialize the query (in our case to json). Fails, because the data class contains a function which can not be serialized.
As a consequence, the distributed queryGateway for axon server can not be used to query the view projection, a workaround is to manually configure the SimpleQueryBus bean.

### Expected behaviour

Queries can be serialized by any standard (XStream, Jackson) serializer configured with axon.

### Actual behaviour

Serialization fails.

**Comment by zambrovski** [comment]
I created a test:
https://github.com/holunda-io/camunda-bpm-taskpool/blob/779b2bb402e54c602dfceb569443593528299d97/view/view-api/src/test/kotlin/query/task/TaskWithDataEntriesForUserQueryTest.kt#L55

We could put it into the jackson-bus as additional Mixin...

Do you want to provide a PR for fixing?

**Comment by zambrovski** [comment]
So as a workaround you need to add a one-liner mixin to your Jackson config...

**Comment by jangalinski** [comment]
Will check tomorrow and provide PR
