### ISSUE TITLE
Enable generation of polyflow properties metadata

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/camunda-bpm-taskpool#564]
### Scenario

* camunda-bpm-taskpool version: 3.2.0
* Camunda BPM version: 7.16.0

### Current Behaviour

While editing the yaml to set up the required properties, IDEA marks the elements yellow and says: `Cannot resolve configuration property 'polyflow.xxx.xxx'

### Wanted Behaviour

polyflow properties support spring boot properties and suggest auto-completion

**Comment by zambrovski** [comment]
Activate annotation (kapt) processing with Spring Annotation processor.
