### ISSUE TITLE
Refactor tasklist and introduce ngrx to hold the query and the tasks

### ISSUE THREAD

**Issue by zambrovski** [holunda-io/camunda-bpm-taskpool#57]

**Comment by jangalinski** [comment]
I had to google: https://github.com/ngrx

**Comment by zambrovski** [comment]
That is what you call redux-style data representation. Using the reducers and selectors.

**Comment by dthuesen** [comment]
Do we really need such a boilerplate for this minimum kind of app?

**Comment by zambrovski** [comment]
Currently, the task list is a demo. So it is more about to show how to build that and how to unterträte with the backend.

I see multiple reasons why this can be helpful. The user should input filter and search criteria. The task list should eventually be reactive and have a mean of automatically update, if the tasks get updated in one of the engines.
