### ISSUE TITLE
Use Optional for nullable query results

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/camunda-bpm-taskpool#578]
While implementing #566 I noticed, that some Task queries uses a nullable `Task?` result.
I would prefer using Java `Optional` here and use the Axon `ResponseTypes.optionalOf(...)` for query execution.

The queries with changed results are all parts of the Task API:

- `TaskApi`
  - `TaskForIdQuery`
  - `TaskWithDataEntriesForIdQuery`
- `ReactiveTaskApi`
  - `TaskForIdQuery`
  - `TaskWithDataEntriesForIdQuery`

In a new API all these queries return `Optional` of the target type instead of Kotlin's nullable type (`T?`). 

This is a breaking change to Polyflow <= 3.5.0.

**Comment by zambrovski** [comment]
This is a good idea. Optional in query results was introduced after I designed the API (at least as far as I know) - so yes. Optional seems nice from the Java point of view but is even more complex to use out of Kotlin.... Let's go for it

**Comment by zambrovski** [comment]
Breaking change - should be at least in a minor release...

**Comment by jangalinski** [comment]
Should we do this for 3.3.0 while adding the potentially breaking changes to the view-api data classes?

**Comment by jangalinski** [comment]
No ... moved to 3.4.0

**Comment by zambrovski** [comment]
Moved to 3.6.0
