### ISSUE TITLE
Question: Can DataEntryForIdentity have multiple results?

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/camunda-bpm-taskpool#579]
if "yes": then ist should be renamed to `DataEntriesForIdentityQuery`, clearly indicating multiple results.

if "no":  the queryHandler should return an Optional result of a single DataEntry instead of the `DataEntriesQueryResult`.

**Comment by zambrovski** [comment]
API breaking - no matter what the answer is

**Comment by jangalinski** [comment]
Well we could provide additional queries and deprecate the "confusing" ones ... that would not immediately break anything.

**Comment by jangalinski** [comment]
Moved to 3.4.0 so it does not block the next release
