### ISSUE TITLE
Suddenly a build failrure in tasklist-react

### ISSUE THREAD

**Issue by zambrovski** [holunda-io/camunda-bpm-taskpool#62]
I believe this worked already, but now, I got a build error. Building on Linux without npm installation globally.

```
[INFO] > cmd-task-list@0.1.0 build /home/simon/projects/camunda-bpm-taskpool/examples/tasklist-react
[INFO] > react-scripts build
[INFO] 
[ERROR] sh: 1: react-scripts: not found
[ERROR] npm ERR! file sh
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno ENOENT
[ERROR] npm ERR! syscall spawn
[ERROR] npm ERR! cmd-task-list@0.1.0 build: `react-scripts build`
[ERROR] npm ERR! spawn ENOENT
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the cmd-task-list@0.1.0 build script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/simon/.npm/_logs/2018-11-08T08_20_35_200Z-debug.log

```

Any ideas?

**Comment by dthuesen** [comment]
I think, without npm you won't have any luck to run it. My suggestion: install nvm on your machine, when you change into the project directory of tasklist-react nvm reads the .nvmrc file and changes automatically to the required node and npm version. If you haven't installed the needed version of node (which includes the right npm version) nvm will promt you or will do it for you. That's easy and should resolve your issue.

**Comment by zambrovski** [comment]
Sorry, please check how this works for Angular 6 tasklist (`tasklist-angular`) and do the same. It is a matter of the `pom.xml` to select the correct `npm` and `node` version to run and a matter of correct `package.json` to install all dependencies.

**Comment by zambrovski** [comment]
Some further details. `mvn clean install -Pnpm-update` was not solving the problem. Manually deleting the folders `node`and `node_modules` solved the problem. I'll close this issue for a moment and we will observe how it behaves in the future. 

Travis CI cleans the entire directory and it works there, but the incremental build should also work....
