### ISSUE TITLE
Reflect changes to IdentityLinks

### ISSUE THREAD

**Issue by lbilger** [holunda-io/camunda-bpm-taskpool#69]
When I change the IdentityLinks of a task after it is created, the change does not seem to be reflected in the task pool.
I used the [REST API](https://docs.camunda.org/manual/7.9/reference/rest/task/identity-links/post-identity-link/) to add a candidate group:
`curl -X POST -H 'Content-Type: application/json' 'localhost:8080/rest/task/ed8fa515-e346-11e8-9c31-e2c74fb4c7e0/identity-links' -d '{"type":"candidate", "groupId": "another_group"}'`

**Comment by zambrovski** [comment]
I believe there is no simple hook on that. We could subscribe to history changes... Or for the moment just not use the REST API.

**Comment by zambrovski** [comment]
See #74
