### ISSUE TITLE
DataEntry not correlated correctly when using filter strings (simple view)

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/camunda-bpm-taskpool#723]
### Steps to reproduce

I have a user task with a correlated data entry.

When I query with:

```
queryGateway.taskWithDataEntriesForId( TaskWithDataEntriesForIdQuery(taskId) )
```
or
```
queryGateway.tasksForUser(TasksForUserQuery(user = polyflowUser))
```

I get a `TaskWithDataEntries` instance representing the task.

But when I use filter Strings to get the same task:

```
queryGateway.tasksWithDataEntriesForUser(TasksWithDataEntriesForUserQuery(user = user.polyflowUser, filters = filters))
```

The returned result **does not** contain the data entry, which makes filter strings useless in this case.

Details: The query by id returns 3 data entries, the query via filter just one of those 3 ...

* camunda-bpm-taskpool version: 3.5.0
* Camunda BPM version: 7.18
* JDK version:  11.05

**Comment by jangalinski** [comment]
Update: It's not the filters ... "byId" I get task + three dataEntries, "forUser" I get task + one dataEntry.

**Comment by zambrovski** [comment]
Update: 
- the `FindTaskWithDataEntriesById` is not tolerating the correlation keys.
