### ISSUE TITLE
Support additional filter operator "oneOf" for filtering tasks and data entries

### ISSUE THREAD

**Issue by tobiasstamann** [holunda-io/camunda-bpm-taskpool#757]
### Current Behaviour
Currently there are already some operators supported by the task list api like <,>,=.

### Wanted Behaviour
We need another operator that supports an "in"/"one of" operator where the value must be equal to one of the passed values.
The syntax could be like : <attributeName>=<value 1>|<value 2>|...

### Possible Workarounds
There's no possibility to achieve this with the given filter operators

**Comment by zambrovski** [comment]
Currently a very good-looking workaround exists with #836. Closing this.

**Comment by zambrovski** [comment]
Will not be implemented until someone wants exactly this again.
