### ISSUE TITLE
taskService.saveTask() without changes causes NoHandlerForCommandException 

### ISSUE THREAD

**Issue by lbilger** [holunda-io/camunda-bpm-taskpool#769]
### Steps to reproduce

* camunda-bpm-taskpool version:
* Camunda BPM version: 3.8.1
* JDK version:  11
* Operating system: MacOS
* Complete executable reproducer: consider the following test method added to `TaskCollectorITest`:
  ```kotlin
  @Test
  fun `updates attributes via API with update listener when nothing changed`() {

    // deploy
    driver.deployProcess(
      createUserTaskProcess(
        taskListeners = listOf(
          "update" to "#{changeTaskAttributes}"
        )
      )
    )

    // start
    val instance = driver.startProcessInstance()
    driver.assertProcessInstanceWaitsInUserTask(instance)
    verify(commandListGateway).sendToGateway(listOf(createTaskCommand()))

    // trigger the update event on the task
    taskService.saveTask(task())

    val updateCommand = updateTaskCommand()
    verify(commandListGateway).sendToGateway(listOf(updateCommand))

    verifyNoMoreInteractions(commandListGateway)
  }
  ```

This is a slight variation on `updates attributes via API with update listener` where nothing is actually changed in the task. This might seem futile but in our setup, it is used to force a task update after process variables have changed.

The command sent to the gateway is not an `UpdateAttributeTaskCommand` but an `UpdateAttributesHistoricTaskCommand`. From that class's description: `This command has no command handler in the core and is never sent to it.`
It is not intended to be sent to the gateway but should be merged into other commands by the accumulator, which doesn't happen if it's the only command. 

So the problem is that without changes to the task, no `UpdateAttributeTaskCommand` is created and thus the `UpdateAttributesHistoricTaskCommand` stands alone where it never should.

* Steps: In a real-world setup, you can reproduce this by calling `taskService.saveTask()` with an original, unchanged task.

### Expected behaviour

Calling saveTask() with no changes to the task itself should create an `UpdateAttributeTaskCommand` enriched with the current process variables.

### Actual behaviour

An `UpdateAttributesHistoricTaskCommand` is issued which cannot be processed and an exception is thrown:
```
org.axonframework.commandhandling.NoHandlerForCommandException: No handler was subscribed for command [io.holunda.camunda.taskpool.api.task.UpdateAttributesHistoricTaskCommand].
```

**Comment by zambrovski** [comment]
Nice one... Side effects over side effects... Thank you for reporting. Are you already working on a solution? 

Without looking on he code, I can think of a filter inside the collector, determining that the `historic update` command is sent alone and transfers that into an update command then...

**Comment by zambrovski** [comment]
Reopening this, because the merged PR turned the pipeline red.
