### ISSUE TITLE
Convert data types for JPA Views' name and description fields (task, data entry, process definition) from @Lob to simple String column

### ISSUE THREAD

**Issue by zambrovski** [holunda-io/camunda-bpm-taskpool#791]
### Scenario

* camunda-bpm-taskpool version: 3.9.1
* Camunda BPM version: 7.18
* Description of your use case: There is no effective way to search in lobs. Consider switching to simple columns with texts stored directly in the table space.

### Current Behaviour

name and descriptions are lobs

### Wanted Behaviour

name and descriptions are strings

### Possible Workarounds

none

**Comment by zambrovski** [comment]
@lbilger I'll need some testing of this feature on your side, to make sure we don't break existing functionality entirely.

**Comment by lbilger** [comment]
I don't think we have any names or descriptions exceeding the maximum varchar column length but I can check to be sure.
