### ISSUE TITLE
Polyflow JPA view: Sort ignores direction

### ISSUE THREAD

**Issue by StephanStrehlerCGI** [holunda-io/camunda-bpm-taskpool#822]
### Steps to reproduce

1. Adding direction order check to SpecificationTest#'creates a paged request'
1. Running test

* camunda-bpm-taskpool version: latest
* Camunda BPM version: -
* JDK version:  11
* Operating system: Windows 10
* Complete executable reproducer: merge request follows directly
* Steps: -

### Expected behaviour
first char '+' should return a ascending result
first char '-' should return a descending result

### Actual behaviour

default sort direction of JPA is used ignoring first char. 
Internally it throws an IllegalArgumentException in Sort.Direction.fromString

(In case of exceptions provide full stack trace)

**Comment by zambrovski** [comment]
Thanks for reporting and for the fix.
