### ISSUE TITLE
Support multiple sort criterias

### ISSUE THREAD

**Issue by MichaelVonB** [holunda-io/camunda-bpm-taskpool#847]
### Scenario

* camunda-bpm-taskpool version: 3.14.2
* Camunda BPM version: any
* Description of your use case: 
Currently it is only possible to sort by one property using  `<+|->fieldName`. If the provided sort has many same values it would be good to add another sort criteria to specify how elements with the same property should be sorted further.

### Current Behaviour
`sort = <+|->fieldName`

### Wanted Behaviour
`sort = List<<+|->fieldName>`

### Possible Workarounds
no good ones, but:
- sort queries result (performance,  does not work with paging)
- sort in frontend (performance)

**Comment by zambrovski** [comment]
@MichaelVonB are you working on this? Please set the tag to "in progress" then, please
