### ISSUE TITLE
Support Camunda 7.20 / Spring Boot 3

### ISSUE THREAD

**Issue by lbilger** [holunda-io/camunda-bpm-taskpool#852]
### Scenario

Spring boot 2.7 is going end-of-life soon (2023-11-18) (see [Spring docs](https://spring.io/projects/spring-boot#support)). We need to update to 3.x, which is supported by Camunda 7.20 according to [their docs](https://docs.camunda.org/manual/latest/user-guide/spring-boot-integration/version-compatibility/). There should be a version of Polyflow that supports these new versions.

I created the milestone 4.0. Let's collect all issues there

**Comment by zambrovski** [comment]
I started to upgrade libraries, we are using here.
