### ISSUE TITLE
Taskpool breaks deleting a process through Cockpit

### ISSUE THREAD

**Issue by lbilger** [holunda-io/camunda-bpm-taskpool#94]
When deleting a process that is currently waiting in a User Task through the Cockpit, I see an error message stating that the process is already deleted.

What seems to be happening is that the event is registered to be fired after transaction completion. When it is fired, the enricher tries to load data of the execution which by that time does not exist anymore.

The same _might_ (not tested) happen when completing a task that has no async-after flag set and that has no other asynchronous activities between itself and the process end event.

**Comment by zambrovski** [comment]
That makes sence! And it is a bug.
