### ISSUE TITLE
Support for Spring-Boot 3.2

### ISSUE THREAD

**Issue by DanielGoals** [holunda-io/camunda-bpm-taskpool#994]
### Scenario

* camunda-bpm-taskpool version: current
* Camunda BPM version: 7.21
* Description of your use case: I want to make sure polyflow supports spring-boot 3.2.

### Current Behaviour
Camunda plattform 7.21 end of support for spring-boot 3.1, while polyflow uses spring-boot 3.1 and camunda 7.21.

### Wanted Behaviour
Use spring-boot 3.2.

### Possible Workarounds
Supply missing dependencies on your own.

**Comment by pschalk** [comment]
I'll have a look

**Comment by zambrovski** [comment]
Fixed by #995
